### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by Troyciv** [Jonathas-Conceicao/Conjuga-Me-Java#3]
when using conjugame, e.g. `conjugame ir`, I get the following output with some error at the beginning.

````
java.io.FileNotFoundException: /opt/ConjugaMe/ser (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at storage.VerboStorage.writeVerbo(VerboStorage.java:45)
	at conjugame.Main.main(Main.java:49)
Conjuga-Me: Conjugação do verbo ser
Gerúndio: sendo	Particípio Passado: sido
                                          INDICATIVO
Presente                                  Pretérito perfeito                        Pretérito imperfeito
eu sou                                    eu fui                                    eu era                                    
tu és                                     tu foste                                  tu eras                              
...
...
````

**Comment by Jonathas-Conceicao** [comment]
I have added a *chmod 666 $PATH* in the install script, remove the old folder and install again and it should work fine now.
